version: '3'
services:
  core:
    build: ./core
    container_name: core
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./core/:/usr/app/
    depends_on:
      - auth
      - data
  auth:
    build: ./auth
    container_name: auth
    ports:
      - 3001:3001
    volumes:
      - /app/node_modules
      - ./auth/:/usr/app/
  data:
    build: ./data
    container_name: data
    ports:
      - 3002:3002
    volumes:
      - /app/node_modules
      - ./data/:/usr/app/